# Generated by Django 4.1.7 on 2023-04-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beautiful_locations',
            new_name='Beautiful',
        ),
    ]
